language: go

sudo: required

branches:
  only:
    - master

services:
  - docker

env:
  - DOCKER_COMPOSE_VERSION: 1.8.0

go:
  - 1.9
  - "1.10"
  - "1.11"
  - "1.12"

before_install:
  - go get github.com/mattn/goveralls
  - go get golang.org/x/tools/cmd/cover
  - sudo rm /usr/local/bin/docker-compose
  - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin
  - docker-compose up -d

script:
  - $HOME/gopath/bin/goveralls -service=travis-ci
