language: go

sudo: required

branches:
  only:
    - master

services:
  - mongodb

go:
  - 1.9
  - "1.10"
  - "1.11"
  - "1.12"

before_install:
  - go get github.com/mattn/goveralls
  - go get golang.org/x/tools/cmd/cover
  - sleep 15
  - mongo --version
  - mongo mongotest --eval 'db.createUser({user:"root",pwd:"password",roles:["root"]});'

script:
  - $HOME/gopath/bin/goveralls -service=travis-ci
